= Webauthn4JS {nbsp}{nbsp}{nbsp} image:https://gitlab.com/davedoesdev/webauthn4js/badges/master/pipeline.svg[pipeline status,link=https://gitlab.com/davedoesdev/webauthn4js/pipelines] image:https://gitlab.com/davedoesdev/webauthn4js/badges/master/coverage.svg[coverage report,link="https://gitlab.com/davedoesdev/webauthn4js/builds/artifacts/master/download?job=ci"] image:https://img.shields.io/npm/v/webauthn4js.svg[NPM version,link=https://www.npmjs.com/package/webauthn4js]
:prewrap!:

This library handles https://w3c.github.io/webauthn/[Web Authentication] for
Node.js applications that wish to implement a passwordless solution for users.

It's implemented as bindings to the
https://github.com/duo-labs/webauthn[Duo Labs Go WebAuthn library], which has
been compiled to Web Assembly. It was inspired by
https://github.com/pulsejet/go-webauthn-js[go-webauthn-js] but uses Go's
built-in Web Assembly compiler instead of GopherJS.

== Example

Here's an example program which uses Webauthn4JS to register and authenticate
users. It uses https://github.com/fastify/fastify[Fastify] to run a Web server
with handlers to allow users to register and login.

A <<index.js,corresponding Web page>> uses the Web Authentication browser API
to interact with the user's authenticator, such as a FIDO2 token, and then makes
requests to the server.

The example is modelled after
https://github.com/hbolimovsky/webauthn-example[this example] of the Duo Labs
library. Users are stored in memory so have to re-register when the server
is restarted. In a real implementation, you'd store users in a database.

I'll describe the example bit-by-bit below. You can also find it in
link:test/example.mjs[]. Run it using:

[source,bash]
----
node --harmony-top-level-await test/example.mjs
----

[source,javascript]
.example.mjs
----
import fs from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import mod_fastify from 'fastify';
import fastify_static from 'fastify-static';
import sodium_plus from 'sodium-plus';
const { SodiumPlus } = sodium_plus;
import makeWebAuthn from 'webauthn4js';
const readFile = fs.promises.readFile;
----

First the imports. Notice that ``webauthn4js```'s default export is a factory
function which will let us make an object to handle Web Authentication requests.
Besides the Fastify imports, we'll also be using
https://github.com/paragonie/sodium-plus[sodium-plus] to sign session data so
it can't be tampered with.

[source,javascript]
----
const challenge_timeout = 60000;
const port = 3000;

const __dirname = dirname(fileURLToPath(import.meta.url));
----

Web Authentication uses challenges sent by the server to the browser, which
the user's authenticator signs in order to prove possession of its public key.
Here we specify a timeout for these challenges so they're not valid forever.
Also, we define the port number that the server will listen on and find the
directory on the filesystem that we're running from.

[source,javascript]
----
const users = new Map();
----

The users are kept in memory, indexed by their username.

[source,javascript]
----
class ErrorWithStatus extends Error {
    constructor(message, statusCode) {
        super(message);
        this.statusCode = statusCode;
    }
}

const keys_dir = join(__dirname, 'keys');

const fastify = mod_fastify({
    logger: true,
    https: {
        key: await readFile(join(keys_dir, 'server.key')),
        cert: await readFile(join(keys_dir, 'server.crt'))
    }
});

fastify.register(fastify_static, {
    root: join(__dirname, 'fixtures'),
    index: 'example.html'
});

const webAuthn = await makeWebAuthn({
    RPDisplayName: 'WebAuthnJS',
    RPID: 'localhost',
    RPOrigin: `https://localhost:${port}`,
    RPIcon: `https://localhost:${port}/logo.png`,
    AuthenticatorSelection: {
        userVerification: 'preferred'
    }
});

const sodium = await SodiumPlus.auto();
const session_data_key = await sodium.crypto_secretbox_keygen();

async function make_secret_session_data(username, type, session_data) {
    const nonce = await sodium.randombytes_buf(
        sodium.CRYPTO_SECRETBOX_NONCEBYTES);
    return {
        ciphertext: (await sodium.crypto_secretbox(
            JSON.stringify([ username, type, session_data, Date.now() ]),
            nonce,
            session_data_key)).toString('base64'),
        nonce: nonce.toString('base64')
    };
}

async function verify_secret_session_data(
    expected_username,
    expected_type,
    secret_session_data) {
    try {
        const [ username, type, session_data, timestamp ] = JSON.parse(
            await sodium.crypto_secretbox_open(
                Buffer.from(secret_session_data.ciphertext, 'base64'),
                Buffer.from(secret_session_data.nonce, 'base64'),
                session_data_key));
        if (username !== expected_username) {
            throw new Error('wrong username');
        }
        if (type !== expected_type) {
            throw new Error('wrong type');
        }
        if ((timestamp + challenge_timeout) <= Date.now()) {
            throw new Error('session timed out');
        }
        return session_data;
    } catch (ex) {
        ex.statusCode = 400;
        throw ex;
    }
}

async function register(fastify) {
    fastify.get('/:username',  async request => {
        let user = users.get(request.params.username);
        if (!user) {
            user = {
                id: `user${users.size}`,
                name: request.params.username,
                displayName: request.params.username.split('@')[0],
                iconURL: '',
                credentials: []
            };
            users.set(request.params.username, user);
        }
        const excludeCredentials = user.credentials.map(c => ({
            type: 'public-key',
            id: c.ID
        }));
        const { options, sessionData } = await webAuthn.beginRegistration(
            user,
            cco => {
                cco.excludeCredentials = excludeCredentials;
                return cco;
            });
        return {
            options,
            session_data: await make_secret_session_data(
                request.params.username, 'registration', sessionData)
        };
    });

    fastify.put('/:username', async (request, reply) => {
        const user = users.get(request.params.username);
        if (!user) {
            throw new ErrorWithStatus('no user', 404);
        }
        const session_data = await verify_secret_session_data(
            request.params.username, 'registration', request.body.session_data);
        let credential;
        try {
            credential = await webAuthn.finishRegistration(
                user, session_data, request.body.ccr);
        } catch (ex) {
            ex.statusCode = 400;
            throw ex;
        }
        for (const u of users.values()) {
            if (u.credentials.find(c => c.ID === credential.ID)) {
                throw new ErrorWithStatus('credential in use', 409);
            }
        }
        user.credentials.push(credential);
        reply.code(204);
    });
}

async function login(fastify) {
    fastify.get('/:username',  async request => {
        const user = users.get(request.params.username);
        if (!user) {
            throw new ErrorWithStatus('no user', 404);
        }
        const { options, sessionData } = await webAuthn.beginLogin(user);
        return {
            options,
            session_data: await make_secret_session_data(
                request.params.username, 'login', sessionData)
        };
    });

    fastify.post('/:username', async (request, reply) => {
        const user = users.get(request.params.username);
        if (!user) {
            throw new ErrorWithStatus('no user', 404);
        }
        const session_data = await verify_secret_session_data(
            request.params.username, 'login', request.body.session_data);
        let credential;
        try {
            credential = await webAuthn.finishLogin(
                user, session_data, request.body.car);
        } catch (ex) {
            ex.statusCode = 400;
            throw ex;
        }
        if (credential.Authenticator.CloneWarning) {
            throw new ErrorWithStatus('credential appears to be cloned', 403);
        }
        const user_cred = user.credentials.find(c => c.ID === credential.ID);
        if (!user_cred) {
            // Should have been checked already in Go by webAuthn.finishLogin
            throw new ErrorWithStatus('no credential', 500);
        }
        user_cred.Authenticator.SignCount = credential.Authenticator.SignCount;
        reply.code(204);
    });
}

fastify.register(register, {
    prefix: '/register/'
});

fastify.register(login, {
    prefix: '/login/'
});

await fastify.listen(port);

console.log(`Please visit https://localhost:${port}`);

----
