= Webauthn4JS {nbsp}{nbsp}{nbsp} image:https://gitlab.com/davedoesdev/webauthn4js/badges/master/pipeline.svg[pipeline status,link=https://gitlab.com/davedoesdev/webauthn4js/pipelines] image:https://gitlab.com/davedoesdev/webauthn4js/badges/master/coverage.svg[coverage report,link="https://gitlab.com/davedoesdev/webauthn4js/builds/artifacts/master/download?job=ci"] image:https://img.shields.io/npm/v/webauthn4js.svg[NPM version,link=https://www.npmjs.com/package/webauthn4js]
:prewrap!:

This library handles https://w3c.github.io/webauthn/[Web Authentication] for
Node.js applications that wish to implement a passwordless solution for users.

It's implemented as bindings to the
https://github.com/duo-labs/webauthn[Duo Labs Go WebAuthn library], which has
been compiled to Web Assembly. It was inspired by
https://github.com/pulsejet/go-webauthn-js[go-webauthn-js] but uses Go's
built-in Web Assembly compiler instead of GopherJS.

== Example

Here's an example program which uses Webauthn4JS to register and authenticate
users. It uses https://github.com/fastify/fastify[Fastify] to run a Web server
with handlers to allow users to register and login.

A <<index.js,corresponding Web page>> uses the Web Authentication browser API
to interact with the user's authenticator, such as a FIDO2 token, and then makes
requests to the server.

The example is modelled after
https://github.com/hbolimovsky/webauthn-example[this example] of the Duo Labs
library.

=== Server-side

Users are stored in memory so have to re-register when the server is restarted.
In a real implementation, you'd store users in a database.

I'll describe the example bit-by-bit below. You can also find it in
link:test/example.mjs[]. Run it using:

[source,bash]
----
node --harmony-top-level-await test/example.mjs
----

[source,javascript]
.example.mjs
----
import fs from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import mod_fastify from 'fastify';
import fastify_static from 'fastify-static';
import { make_secret_session_data, verify_secret_session_data } from './session.mjs';
import makeWebAuthn from 'webauthn4js';
const readFile = fs.promises.readFile;
----

First the imports. Notice that ``webauthn4js```'s default export is a factory
function which will let us make an object to handle Web Authentication
registration and login.

[source,javascript]
----
const port = 3000;
const __dirname = dirname(fileURLToPath(import.meta.url));
----

Here we define the port number that the server will listen on and find the
directory on the filesystem that we're running from.

[source,javascript]
----
const users = new Map();
----

The users are kept in memory, indexed by their username.

[source,javascript]
----
class ErrorWithStatus extends Error {
    constructor(message, statusCode) {
        super(message);
        this.statusCode = statusCode;
    }
}
----

Fastify uses `statusCode` properties on thrown `Error` objects to return HTTP
status codes to the browser. This is just a convenience class.

[source,javascript]
----
const keys_dir = join(__dirname, 'keys');

const fastify = mod_fastify({
    logger: true,
    https: {
        key: await readFile(join(keys_dir, 'server.key')),
        cert: await readFile(join(keys_dir, 'server.crt'))
    }
});

fastify.register(fastify_static, {
    root: join(__dirname, 'fixtures'),
    index: 'example.html'
});
----

Here we configure Fastify to serve over HTTPS the Web page users will use to
interact with their authenticators.

[source,javascript]
----
const webAuthn = await makeWebAuthn({
    RPDisplayName: 'WebAuthnJS',
    RPID: 'localhost',
    RPOrigin: `https://localhost:${port}`,
    RPIcon: `https://localhost:${port}/logo.png`,
    AuthenticatorSelection: {
        userVerification: 'preferred'
    }
});
----

Now we make our link:docs.html#WebAuthn4JS[`WebAuthn4JS`] object which will
handle registration and login. Note this example assumes it's running on
`localhost`.

[source,javascript]
----
async function register(fastify) {
    fastify.get('/:username', async request => {
        let user = users.get(request.params.username);
        if (!user) {
            user = {
                id: `user${users.size}`,
                name: request.params.username,
                displayName: request.params.username.split('@')[0],
                iconURL: '',
                credentials: []
            };
            users.set(request.params.username, user);
        }
----

We set up a GET handler to start the registration of a new credential (public key) for a user.
Note in this example we don't verify user name belongs to the requester. In a real application we
might perform email verification or generate unguessable user names, for example.

We generate a unique ID and maintain a list of credentials for each user and store this information
in the `users` `Map`.

[source,javascript]
----
        const excludeCredentials = user.credentials.map(c => ({
            type: 'public-key',
            id: c.ID
        }));
----

This is a list of credentials that the user shouldn't use for registering with this server.
We specify here that the browser shouldn't use any credential that the user has already registerd.

[source,javascript]
----
        const { options, sessionData } = await webAuthn.beginRegistration(
            user,
            cco => {
                cco.excludeCredentials = excludeCredentials;
                return cco;
            });
----

Now we begin registration, calling link:docs.html#WebAuthn4JS[`beginRegistration`] and passing in
the user and the excluded (existing) credentials.

[source,javascript]
----
        return {
            options,
            session_data: await make_secret_session_data(
                request.params.username, 'registration', sessionData)
        };
    });
----

Once registration has started, we need to return data to the browser so it can ask the user to
register using their authenticator. We return the options that WebAuthn4JS generates for the
browser's `navigator.credentials.create()` call, along with session data that WebAuthn4JS will check
when the browser makes its PUT request to complete registration. Note we sign and encrypt this data
to ensure it won't be tampered with.

[source,javascript]
----
    fastify.put('/:username', async (request, reply) => {
        const user = users.get(request.params.username);
        if (!user) {
            throw new ErrorWithStatus('no user', 404);
        }
----

We set up a PUT handler to complete a registration previously started with a GET request for the
same user. If the user doesn't exist then registration wasn't started and a 404 error is returned.

[source,javascript]
----
        const session_data = await verify_secret_session_data(
            request.params.username, 'registration', request.body.session_data);
----

First we verify the session data to ensure it hasn't been tampered with.

[source,javascript]
----
        let credential;
        try {
            credential = await webAuthn.finishRegistration(
                user, session_data, request.body.ccr);
        } catch (ex) {
            ex.statusCode = 400;
            throw ex;
        }
----

Then we complete the registration process, calling link:docs.html#WebAuthn4JS[`finishRegistration`] 
and receiving a link:docs.html#WebAuthn4JS[`Credential`] object. Note the credential isn't yet
associated with a user.

[source,javascript]
----
        for (const u of users.values()) {
            if (u.credentials.find(c => c.ID === credential.ID)) {
                throw new ErrorWithStatus('credential in use', 409);
            }
        }
----

If the credential is in use by any user already, this is an error.

[source,javascript]
----
        user.credentials.push(credential);
        reply.code(204);
    });
}
----

Finally for registration, we associate the credential with the requested user.

[source,javascript]
----
async function login(fastify) {
    fastify.get('/:username', async request => {
        const user = users.get(request.params.username);
        if (!user) {
            throw new ErrorWithStatus('no user', 404);
        }
        const { options, sessionData } = await webAuthn.beginLogin(user);
        return {
            options,
            session_data: await make_secret_session_data(
                request.params.username, 'login', sessionData)
        };
    });
----

Login's GET handler first checks the user exists and then calls
link:docs.html#WebAuthn4JS[`beginLogin`], passing in the user object. We then return to the browser
the options for `navigator.credentials.get()` and signed and encrypted session data.

[source,javascript]
----

    fastify.post('/:username', async (request, reply) => {
        const user = users.get(request.params.username);
        if (!user) {
            throw new ErrorWithStatus('no user', 404);
        }
        const session_data = await verify_secret_session_data(
            request.params.username, 'login', request.body.session_data);
----

Login's POST handler checks the user exists and verifies the session data it received from the
browser.

[source,javascript]
----
        let credential;
        try {
            credential = await webAuthn.finishLogin(
                user, session_data, request.body.car);
        } catch (ex) {
            ex.statusCode = 400;
            throw ex;
        }
----

It then completes the login process by calling link:docs.html#WebAuthn4JS[`finishLogin`], passing in
the user object, session data and authentication request it received from the browser (i.e. the
result of `navigator.credentials.get()`).

[source,javascript]
----
        if (credential.Authenticator.CloneWarning) {
            throw new ErrorWithStatus('credential appears to be cloned', 403);
        }
        const user_cred = user.credentials.find(c => c.ID === credential.ID);
        if (!user_cred) {
            // Should have been checked already in Go by webAuthn.finishLogin
            throw new ErrorWithStatus('no credential', 500);
        }
----

Here we do a couple of checks on the credential used for login:

* The credential hasn't been cloned, i.e. we received a duplicate login request from the same
  authenticator. This is actually checked by the underlying Go WebAuthn library.
* The credential belongs to the requested user. Again, this should have already been checked in Go.

[source,javascript]
----
        user_cred.Authenticator.SignCount = credential.Authenticator.SignCount;
        reply.code(204);
    });
}
----

Finally for login, we have to update the `SignCount` for the credential in the user's credentials
list. This enables the Go library to check for duplicate requests.

[source,javascript]
----
fastify.register(register, {
    prefix: '/register/'
});

fastify.register(login, {
    prefix: '/login/'
});

await fastify.listen(port);

console.log(`Please visit https://localhost:${port}`);
----

The server-side code ends by registering our handlers with Fastify and then listening for requests.

[[index.js]]
=== Browser-side
