name: ci

on: [push, pull_request]

env:
    CI: true

jobs:
    test:
        strategy:
            matrix:
                node-version: [14]
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2.1.0
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install
              run: npm ci

            - name: Run tests
              uses: GabrielBB/xvfb-action@1.2
              run: npm run test:ci
